### PR TITLE
Remove phrase from 1st issue thank you template which suggests the user erred

### PR DESCRIPTION
**Pull request by joewiz**
To a user who has just submitted their first issue, the phrase "Be sure to follow the issue template!" reads as if the user failed to follow the template.

### CODE REVIEW

**Comment by joewiz** [comment]
See one such user's "thumbs down" reaction to the original phrase: https://github.com/eXist-db/exist/issues/3981#issuecomment-865665587

**Review by duncdrum — APPROVED** [review]

**Comment by duncdrum** [comment]
well yes that was the point, after posting `please follow the issue template` 100 times as a response to first issues.

**Comment by joewiz** [comment]
Perhaps rephrasing it like this would be better?

> If you followed the template, then great! If not, please review the template again and post any missing info. This provides critical context for those reviewing your issue."

I'm happy to submit another PR if you think this would help.

**Comment by sideeffect42** [comment]
Just to clarify: My thumbs down in #3981 was not because of the wording of the message, but because I don't see value in this message at all.

IMHO it's just useless noise.
This bot reply is like the recorded voice saying "your call is very important to us" after you've been waiting for 15min on hold.  
If you would like to embrace users opening issues or thank them for their bug report it would be better to deal with the issue faster and not ignore issues for 4 weeks without a human response.

#jm2c

**Comment by joewiz** [comment]
@sideeffect42 I know the frustration. Apologies if you found yourself in this situation here. For context, though, this is an open source project that relies on community contributors. The community does their best but are unfortunately spread thin. Thus, even modest improvements to automated responses such as these play an important role—of steering people in the right direction so that when someone does respond, they have all of the info that's needed.

**Comment by sideeffect42** [comment]
@joewiz No problems. If the waiting time would've been a biggie for me, I'd have tried to attract some attention to my "issue".

> Thus, even modest improvements to automated responses such as these play an important role—of steering people in the right direction so that when someone does respond, they have all of the info that's needed.

Maybe I'm misunderstanding you here, but I'm not criticising the issue template or something. It is fine.

All I meant to say was that the bot response is neither helpful to attract new "contributors" (because it only appears _after_ a person has decided to open an issue) nor to keep them (because the bot response does nothing to resolve the issue.)

**Comment by joewiz** [comment]
I take your point - but these services can be intimidating to first time contributors, and a simple thanks or praise is a nice touch - especially if it steers the substance of the issue in a productive direction.

**Pull request merged**
