### PR TITLE
Update lucene.xml

### PR DESCRIPTION
**Pull request by sten1ee**
Update lucene.xml, by inserting a short description of the feature introduced by https://github.com/eXist-db/exist/pull/2169

### CODE REVIEW

**Comment by sten1ee** [comment]
Mmm,
I am confused.
I have eXist 4.6.1 cloned, built and running.
It does incorporate the feature that comes with https://github.com/eXist-db/exist/pull/2169 and documented by this very PR.
And nevertheless neither the documentation that comes with eXist 4.6.1 nor the one that is globally available here https://exist-db.org/exist/apps/doc/lucene#D3.19.58 includes the updated documentation about this feature.
How come?

**Comment by duncdrum** [comment]
can you check the version of the documentation app that you've installed locally?

**Comment by sten1ee** [comment]
I don't know how to do that.
Tried, but it is not as obvious as "Help | About"
Instructions, please?

**Comment by duncdrum** [comment]
you can see the currently installed version inside the package-manager, or by checking the `expath-package.xml` file inside `apps/docs/`
Screenshot 2019-04-01 at 20 26 04

P.S.: the 4.6.1 package-manager looks slightly different, but you get the idea.

**Comment by sten1ee** [comment]
None of these works for me, but strangely enough, clicking on the package manager results in nothing, not even a WARN or ERROR in exist.log
It may be the case that I've restored (through bin/backup.sh) an older version of this app.

How about the online documentation -- why is it not there https://exist-db.org/exist/apps/doc/lucene#D3.19.58 ?
And besides (a general remark) it seem that the online documentation is trying to address all supported version of eXist in one version of the docs, as opposed to (e.g.) Lucene's online documentation, where the version of Lucene to which the current doc applies is part of the URL, e.g.: https://lucene.apache.org/core/4_10_4/analyzers-common/org/apache/lucene/analysis/standard/StandardAnalyzer.html

**Comment by duncdrum** [comment]
The online version of the docs is heavily out of date, since exist `4.1.0` local installs will always be the most current for your version. If you restored from a previous install of exist, chances are indeed that you have an old version of the documentation installed. The simple solution is to download the most recent version for exist 4.6.1 from [here](https://github.com/eXist-db/documentation/releases/tag/4.1.1) and install it manually.

**Comment by sten1ee** [comment]
1. How about the 'silent failure' of the package manager?
2. How do I install a xar if the package manager is not working? Guess I need to paste it in a specific directory (sorry for being ignorant here)

**Comment by duncdrum** [comment]
[programmatically installing packages](http://www.exist-db.org/exist/apps/doc/repo.xml?field=all&id=D3.27#D3.27)

**Pull request merged**
