### PR TITLE
Also test against Java 17

### PR DESCRIPTION
**Pull request by adamretter**
Test against the version of Java for eXist-db 6.x.x (Java 8), and eXist-db 7.x.x (Java 17).

Requires https://github.com/eXist-db/documentation/pull/904 to be merged first.

### CODE REVIEW

**Comment by joewiz** [comment]
@adamretter With #904 merged, this is ready for a rebase.

**Comment by adamretter** [comment]
@joewiz Okay I have rebased.

Unfortunately I am now seeing a failure that is unrelated to this PR, which seems to be related to formatting of content of the documentation. I am not sure where that came from. The failure is this:

```
[INFO]   running XQsuite test …
[INFO] response body: {"testsuite":{"package":"http://exist-db.org/xquery/documentation/tests","timestamp":"2023-03-20T14:53:11.759Z","tests":"6","failures":"1","errors":"0","pending":"1","time":"PT3.788S","testcase":[{"name":"Listing consistency","class":"tests:equal-listing"},{"name":"section-headings","class":"tests:missing-id"},{"name":"Pro angular brackets","class":"tests:no-ecaped-listings","failure":{"message":"assertEmpty failed.","type":"failure-error-code-1"},"output":"urlrewrite.xml"},{"name":"wellformed xml","class":"tests:no-txt-xmls","pending":null},{"name":"diagnose listings","class":"tests:orphan-listing"},{"name":"ToC rendering","class":"tests:toc-inline"}]}}
[INFO]         6 xqsuite tests:
[INFO]           Listing consistency
[INFO]           section-headings
[INFO]           [ 'Pro angular brackets', 'assertEmpty failed.' ]
```

I am afraid that I have absolutely no idea what that is or what is meant by `'Pro angular brackets', 'assertEmpty failed.'`. Any ideas?

**Comment by duncdrum** [comment]
@adamretter these test failures were introduced by #872 which you cleaned up

see #928

**Comment by adamretter** [comment]
> @adamretter these test failures were introduced by https://github.com/eXist-db/documentation/pull/872 which you cleaned up

Possibly yes. But I have no idea what these errors mean or how to fix them. There simply isn't enough information... do you know?

**Comment by duncdrum** [comment]
@adamretter see #928 the XQS test returns the list of documents, where xml as string literal appears inside `<programlisting>`. The author guidelines contain a section of why this isn't a good idea.

**Comment by adamretter** [comment]
@joewiz I was in the middle of working on addressing this as @duncdrum had requested... what happened?

**Comment by joewiz** [comment]
@adamretter I didn't close it directly. I think it was closed when I merged https://github.com/eXist-db/documentation/pull/929.

**Comment by duncdrum** [comment]
@adamretter the Java 17 changes are unrelated to the faulty programmlistings which @joewiz fixed in the meantime.

**Comment by duncdrum** [comment]
I didn't mean to cause duplicate work.

**Pull request closed without merging**
