### PR TITLE
Update to Node 14

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/documentation/issues/629

### CODE REVIEW

**Comment by line-o** [comment]
@adamretter this is already part of #626

**Comment by line-o** [comment]
Interestingly you also chose npm version 6
Can you tell me why npm 7 cannot be used?

**Review by line-o — COMMENTED** [review]
good changes but would be conflicting with #626

**Comment by adamretter** [comment]
> @adamretter this is already part of #626

Okay I didn't realise that! Regardless, it should likely be a separate PR otherwise there are mixed concerns... which could explain why I didn't realise it was part of that other PR ;-)

If you download Node v14.17.0, then it comes with npm 6.14.13... So I figured it was best to use the recommended versions.

**Comment by line-o** [comment]
OK, so it is the bundled version.
While I see a separate PR would be nicer it is more important to me to get #626 in as it is what we need for the release of eXistdb

**Comment by adamretter** [comment]
@line-o It's simple enough to have both. Merge this and you/I can rebase the other in minutes ;-)

**Comment by line-o** [comment]
Weird, now the cypress tests are failing in this branch as well. (the sole reason why #626 is not merged yet)

**Comment by joewiz** [comment]
My inclusion of Node 14 in #626 was just a test to see if CI would pass with it. If we get it working here I'll force push a clean branch.

**Comment by adamretter** [comment]
Test failures here are different though I think

**Comment by line-o** [comment]
https://github.com/eXist-db/documentation/pull/638/checks?check_run_id=2795137601#step:6:553
was also reported by @joewiz 
@duncdrum do you have an idea?

**Comment by line-o** [comment]
This is likely the update to cypress 7.4 by the looks of things

**Comment by joewiz** [comment]
And we're green! 

From https://docs.cypress.io/api/commands/visit#Syntax:

> Cypress will prefix the URL with the `baseUrl` configured in your network options if you've set one.

Our cypress.json defines `baseUrl` as `http://localhost:8080/exist/apps/doc/`, so the `cy.visit('.')` in `documentation_spec.js` was causing cypress to request:

`http://localhost:8080/exist/apps/doc/.`

I wasn't able to force a request to `.` with curl to see if I could induce eXist to return the `content-type: application/xml` reported by CI. But, it’s clear that removing the period ensures the request goes to the intended URL:

`http://localhost:8080/exist/apps/doc/`

Once I made this change, `npm run cypress` passed locally, so I committed the change to this branch, and it passes here too.

**Review by joewiz — APPROVED** [review]

**Comment by joewiz** [comment]
My hunch is that https://github.com/cypress-io/cypress/pull/8629, which was released in Cypress 5.3.0, somehow affected our changes to `baseUrl` and the `cy:visit` call in https://github.com/eXist-db/documentation/pull/519. That PR passed CI, so there must be some other variable(s) here... but I think it's pretty clear that the `.` isn't necessary given the definition of `baseUrl`.

**Comment by joewiz** [comment]
I was able to reproduce the request to `http://localhost:8080/exist/apps/doc/.` using Postman. eXist returns the collection contents, as if we'd requested `http://localhost:8080/exist/rest/db/apps/doc`!

> Screen Shot 2021-06-11 at 2 09 10 PM

In my testing, this is the result of the `controller.xql`'s "ignore" directive on "all other requests." One takeaway for users of eXist's URL rewriting facility is that if you don't want your collection contents to be listable (and resources viewable), you definitely shouldn't use an "ignore" fallback; you should implement an error page of some kind and set an appropriate status code.

**Review by duncdrum — APPROVED** [review]
Ah I remember now this being part of the release notes, I would suggest to move to `cy.visit(‘/‘) in a separate future update obviously adjusting the `baseUrl` in the config.

**Pull request merged**
