### PR TITLE
Props and sync

### PR DESCRIPTION
**Pull request by eduarddrenth**
sync fixed and tested
bootstrap updates reverted (building documentation probably updates boot strap, unwanted I think)

### CODE REVIEW

**Comment by joewiz** [comment]
@eduarddrenth Thanks for the updated PR! I checked out your branch and tried to build the package according to the README, using `mvn clean package -DskipTests`, but this ended with an error - which appears to be caused by some schema validation issues. Could you please review these issues?

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.959 s
[INFO] Finished at: 2020-11-28T13:38:04-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.0.2:validate (default) on project exist-documentation: While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/datasync/datasync.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/datasync/datasync.xml, line 50,  column 16: error: element "sect2" not allowed yet; expected element "example", "figure", "important", "informalfigure", "informaltable", "itemizedlist", "note", "orderedlist", "para", "programlisting", "table", "variablelist" or "warning"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/datasync/datasync.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/datasync/datasync.xml, line 50,  column 16: error: element "sect2" missing required attribute "xml:id"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/datasync/datasync.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/datasync/datasync.xml, line 54,  column 33: error: element "programlisting" not allowed here; expected the element end-tag, text or element "code", "emphasis", "guimenuitem", "inlinemediaobject", "link", "literal", "tag" or "xref"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/datasync/datasync.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/datasync/datasync.xml, line 61,  column 16: error: element "sect2" missing required attribute "xml:id"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/datasync/datasync.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/datasync/datasync.xml, line 64,  column 48: error: element "programlisting" not allowed here; expected the element end-tag, text or element "code", "emphasis", "guimenuitem", "inlinemediaobject", "link", "literal", "tag" or "xref"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, line 32,  column 16: error: element "sect2" not allowed yet; expected element "example", "figure", "important", "informalfigure", "informaltable", "itemizedlist", "note", "orderedlist", "para", "programlisting", "table", "variablelist" or "warning"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, line 32,  column 16: error: element "sect2" missing required attribute "xml:id"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, line 36,  column 33: error: element "programlisting" not allowed here; expected the element end-tag, text or element "code", "emphasis", "guimenuitem", "inlinemediaobject", "link", "literal", "tag" or "xref"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, line 43,  column 16: error: element "sect2" missing required attribute "xml:id"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, line 45,  column 50: error: element "programlisting" not allowed here; expected the element end-tag, text or element "code", "emphasis", "guimenuitem", "inlinemediaobject", "link", "literal", "tag" or "xref"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, line 53,  column 16: error: element "sect2" missing required attribute "xml:id"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, line 55,  column 35: error: element "programlisting" not allowed here; expected the element end-tag, text or element "code", "emphasis", "guimenuitem", "inlinemediaobject", "link", "literal", "tag" or "xref"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, line 68,  column 16: error: element "sect2" missing required attribute "xml:id"
[ERROR] While parsing /Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, at file:/Users/joe/workspace/documentation/src/main/xar-resources/data/properties/properties.xml, line 70,  column 58: error: element "programlisting" not allowed here; expected the element end-tag, text or element "code", "emphasis", "guimenuitem", "inlinemediaobject", "link", "literal", "tag" or "xref"
```

**Comment by joewiz** [comment]
p.s. Normally I believe we could've relied on Travis to perform these tests for us on PRs, but I gather from discussion in Slack that the eXist-db GitHub organization exceeded Travis's free allotment of tests, and there's no solution in sight. So for now I think this means we've got to perform tests locally.

**Comment by eduarddrenth** [comment]
> @eduarddrenth Thanks for the updated PR! I checked out your branch and tried to build the package according to the README, using `mvn clean package -DskipTests`, but this ended with an error - which appears to be caused by some schema validation issues. Could you please review these issues?

I'll take a look, a pitty this one because Oxygen says all is well

**Comment by eduarddrenth** [comment]
validates now using mvn validate

**Comment by joewiz** [comment]
@eduarddrenth Great, I can confirm validation now passes.

**Comment by joewiz** [comment]
@eduarddrenth I wonder if there might be any easier method for making this feature available to users of eXist. For example, for users accustomed to building eXist from source via maven, is there something that these users could add to eXist's pom.xml to ensure the proper artifacts are retrieved?

**Comment by eduarddrenth** [comment]
```
<dependency>
  <groupId>org.fryske-akademy</groupId>
  <artifactId>exist-db-addons</artifactId>
  <version>1.7</version>
</dependency>
```
You mean this?

**Comment by eduarddrenth** [comment]
don't know why the build fails. Something changed in build process?

**Comment by adamretter** [comment]
@eduarddrenth These tests are failing:

```
[INFO]   running XQsuite test …
[INFO]         6 xqsuite tests:
[INFO]           Listing consistency
[INFO]           section-headings
[INFO]           [ 'Pro angular brackets', 'assertEmpty failed.' ]
```

Is it possible you have some empty section headings now, or that they are missing an id attribute? The failing tests is this one (I think) - https://github.com/eXist-db/documentation/blob/master/src/main/xar-resources/modules/test-suite.xql#L57

**Comment by eduarddrenth** [comment]
> @eduarddrenth These tests are failing:

So I saw yes, but I did not change a thing except for a new version number of the lib. No emty section headers or other empty things. Is this test new?

**Comment by adamretter** [comment]
@eduarddrenth I am not sure how new the tests are, they were added by @duncdrum. The tests were not being run on CI until recently when they were reinstated.

**Review by joewiz — APPROVED** [review]
As discussed during this week's Community Call, all requests have been addressed, and all tests are passing.

**Comment by joewiz** [comment]
@eduarddrenth Thank you for contributing this article!

**Comment by eduarddrenth** [comment]
Nice!

**Pull request merged**
