### PR TITLE
XMLDBTransformer is deprecated

### PR DESCRIPTION
**Pull request by miljanuscumlic**
I removed the sentence about XMLDBTransformer because there is no doc page about it anymore.

### CODE REVIEW

**Comment by duncdrum** [comment]
@miljanuscumlic thank you for the PR. 
@adamretter, @wolfgangmm, @dizzzz could any of you confirm, I have no idea about ``XMLDBTransformer``

**Comment by miljanuscumlic** [comment]
@duncdrum No problem. This is how I found out it is deprecated : http://memory.loc.gov/exist/devguide_xmldb.xml Its an old version of the page, and it says so.

**Comment by adamretter** [comment]
@duncdrum Oh yes! We dropped Cocoon support went many years ago :-p

@miljanuscumlic Thanks for another good contribution :-)

**Comment by miljanuscumlic** [comment]
@adamretter No worries. I am really glad I can contribute at least in this small way.

**Pull request merged**
