### PR TITLE
Updated the documentation for the Mavenized eXist-db

### PR DESCRIPTION
**Pull request by adamretter**
See #333

### CODE REVIEW

**Comment by joewiz** [comment]
There appear to be other instances of start.jar - the application's search engine seems not to find them all. For example, http://localhost:8080/exist/apps/doc/advanced-installation.xml#bin-executables.

**Comment by adamretter** [comment]
@joewiz I used grep to find them, I think I have fixed them all now and pushed the updates.

**Comment by duncdrum** [comment]
@joewiz about the search, if the string appears in a listing outside of the `db5` file it won't get indexed, that is indeed a problem, i ll have to think about that.

**Comment by adamretter** [comment]
@duncdrum done!

**Comment by adamretter** [comment]
@joewiz thanks :-)

**Comment by adamretter** [comment]
@duncdrum thanks for yours too :-)

**Comment by joewiz** [comment]
Searching for ant turns up two more hits:

- Configuring Database Indexes > Enabling Index Modules
> Call the *Ant* build system once to regenerate the eXist-db libraries using build.sh or build.bat.

- Developer's Guide to Modularized Indexes > Use case: developing an indexing architecture for GML geometries
> In eXist's Git repository, the modularized Indexes code is in extensions/indexes ... The build system should normally be able to download the required libraries and build all the files automatically, in particular the extension-modules *Ant* target,

Also some instances of `build.sh`:

- Full Text Index > Enabling the Lucene Module
    > Then (re-)build eXist-db using the provided *build.sh* or build.bat script. The build process downloads the required Lucene jars automatically. If everything builds ok, you'll find a jar exist-lucene-module.jar in the lib/extensions directory.
- Configuring Database Indexes > Enabling Index Modules
    > Call the Ant build system once to regenerate the eXist-db libraries using *build.sh* or build.bat.

Several cases seem to refer to the old directory layout
- search for "webapp/WEB-INF", e.g.: http://localhost:8080/exist/apps/doc/search.html?q=%22webapp%2FWEB-INF%22&field=all&view=summary&action=&prev=
- search for "tools" or "tools/yajsw" or "tools/jetty", e.g.: http://localhost:8080/exist/apps/doc/search.html?q=%22tools%2Fyajsw%22&field=all&view=summary&action=&prev=

**Comment by adamretter** [comment]
@joewiz Okay, I sent some more updates...

**Comment by duncdrum** [comment]
this CI failure is about a missing section `xml:id`. Future fixes should go into the `5.0.0-RC1` branch thanks.

**Pull request closed without merging**
