### PR TITLE
Add notes on serialization and reverse proxy issues

### PR DESCRIPTION
**Pull request by dizzzz**

### CODE REVIEW

**Comment by funkyfuture** [comment]
the wording is not fully true. it is possible to access WebDAV resources behind a proxy, but the URI's path must be identical in order for `PROPFIND` to work correctly (`MKCOL` and `PUT` do actually work).

**Comment by dizzzz** [comment]
Ok, thnx

**Comment by dizzzz** [comment]
can you help to rewrite the sentence?

**Comment by funkyfuture** [comment]
i hope this helps.

```xml
From the <ulink url="https://github.com/eXist-db/exist/issues/1442">community</ulink> we 
have received feedback that the WebDAV interface is not fully functional when it is
accessed via a reverse proxy and a resource's path is altered (aliased) with it.
```

**Pull request merged**
