### PR TITLE
documentation on properties and synchronization

### PR DESCRIPTION
**Pull request by eduarddrenth**

### CODE REVIEW

**Comment by joewiz** [comment]
@eduarddrenth Thank you - looking forward to checking this out. One question - your PR contains changes to the bootstrap files. Was that intended?

**Comment by duncdrum** [comment]
@joewiz thats normal nothing to worry about

**Comment by joewiz** [comment]
@eduarddrenth Could you confirm if the bootstrap changes were intentional and needed for the PR? If they were not needed, could you open a clean PR (or force push to this branch to remove the unintentional commits)?

**Comment by eduarddrenth** [comment]
> @eduarddrenth Could you confirm if the bootstrap changes were intentional and needed for the PR? If they were not needed, could you open a clean PR (or force push to this branch to remove the unintentional commits)?

unintentional, I have absolutely no clue how these ended up in my pr, never touched these files

**Comment by eduarddrenth** [comment]
Just discovered a problem that files with diacrits in the name are not synced

**Pull request closed without merging**
