### PR TITLE
Fix issues causing gulp to choke

### LINKED ISSUE #731: [BUG] fix build
**Describe the bug**

#726 causes gulp to throw an error:

> Error: Text data outside of root node.

It's not clear which of the newly introduced files caused the problem, but oXygen reports that listing-5.xml, as well as 8, 9, 10, 11, 12, and 13, are not well-formed. they contain content after the root element. 

**Expected behavior**

Validation/linting should catch such issues earlier in the build process, no? 

**To Reproduce**

Clone repo, run gulp.

**Unit Test**

n/a

**Integration Test**

n/a

If none of the above is working, please tell us the exact steps you took when you encountered the problem:

See https://github.com/eXist-db/documentation/actions/runs/1688799320. Repeat CI build steps locally to reproduce.

**Screenshots**

n/a

**Context (please always complete the following information):**
- eXist-db Version: eXist 5.4.0-SNAPSHOT fc0ac70363b37041f42d4ad284cb990653c0d3a6 20220108074211
- App Version: 5.3.1-SNAPSHOT
- Browser Version: Chrome 96.0.4664.110

### PR DESCRIPTION
**Pull request by joewiz**
Closes #731.

I also spotted several of the files in the listings directory that aren't referenced in the article with `<programlisting>`, but my primary goal in this PR is to fix the build.

It would be nice if the build process could catch such errors and flag which files are the cause of the error. These errors weren't caught by `mvn validate`. Only `mvn test` failed - and didn't tell us which file caused the problem.

### CODE REVIEW

**Comment by joewiz** [comment]
The commit that ultimately fixed the build for me locally was [addressing the listings with multiple root nodes](https://github.com/eXist-db/documentation/pull/732/commits/2ca3ceea7c49294e425f4d8be28e053e4e27abd7) - i.e., changing them from .xml to .txt.

**Comment by joewiz** [comment]
CI has failed:

```
[INFO] --- frontend-maven-plugin:1.12.1:npm (mocha tests) @ exist-documentation ---
[INFO] Running 'npm test' in /home/runner/work/documentation/documentation
[INFO] 
[INFO] > exist-documentation@5.3.1-SNAPSHOT test
[INFO] > mocha src/test/mocha/ --recursive --exit
[INFO] 
[INFO] 
[INFO] 
[INFO]   running XQsuite test …
[INFO] response body: {"testsuite":{"package":"http://exist-db.org/xquery/documentation/tests","timestamp":"2022-01-12T18:37:42.981Z","tests":"6","failures":"1","errors":"0","pending":"1","time":"PT2.874S","testcase":[{"name":"Listing consistency","class":"tests:equal-listing"},{"name":"section-headings","class":"tests:missing-id"},{"name":"Pro angular brackets","class":"tests:no-ecaped-listings","failure":{"message":"assertEmpty failed.","type":"failure-error-code-1"},"output":"fo-render.xml"},{"name":"wellformed xml","class":"tests:no-txt-xmls","pending":null},{"name":"diagnose listings","class":"tests:orphan-listing"},{"name":"ToC rendering","class":"tests:toc-inline"}]}}
[INFO]         6 xqsuite tests:
[INFO]           Listing consistency
[INFO]           section-headings
[INFO]           [ 'Pro angular brackets', 'assertEmpty failed.' ]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  46.609 s
[INFO] Finished at: 2022-01-12T18:37:43Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (mocha tests) on project exist-documentation: Failed to run task: 'npm test' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

This is puzzling, because when running unit and integration tests locally as described in the README, they all pass.

Any ideas?

**Comment by joewiz** [comment]
The failing xqsuite test is here: https://github.com/eXist-db/documentation/blob/master/src/main/xar-resources/modules/test-suite.xql#L137-L157.

Running this test locally returns the following output:

```xml
<testcase name="Pro angular brackets" class="tests:no-ecaped-listings">
    <failure message="assertEmpty failed." type="failure-error-code-1"/>
    <output>fo-render.xml</output>
</testcase>
```

So it looks like fo-render.xml contains instances of `<programlisting language="xml"/>`. 

Wouldn't this make more sense to perform this check in Schematron, so that it's caught up front by `mvn validate` instead of waiting for the integration test?

@adamretter In #726 you committed a lot of files to the `listings` directory but didn't update the article to reference them all. Is it possible you made the changes locally but didn't commit the updated `fo-render.xml` file?

**Comment by duncdrum** [comment]
@joewiz the last changes to how integration tests are run locally are from https://github.com/eXist-db/documentation/pull/599  maybe @adamretter has an idea. The errors flagged by CI in the original PR are reported correctly, so they should never have passed running the tests locally. 

```
6 xqsuite tests:
[INFO]           Listing consistency
[INFO]           section-headings
[INFO]           [ 'Pro angular brackets', 'assertEmpty failed.' ]
```

this xqs test very likely predates the schema and schematron rules, so refactoring it to be part of one instead of the other is certainly an option. 

the basic idea that:
- `listingXYZ.xml` listing have to be well-formed
- avoid pure cdata inline xml listings

are both covered in the author guide. So your fixes go in the right direction. 

There should actually be another check to hunt for non-referenced listings, if they exist that's certainly another error.

**Comment by adamretter** [comment]
> avoid pure cdata inline xml listings
> are both covered in the author guide.

Actually the style guide says that using CDATA inline is ok. As that is no longer the case, we should update the style guide...

**Comment by joewiz** [comment]
It does! :)

**Review by line-o — APPROVED** [review]

**Review by dizzzz — APPROVED** [review]

**Comment by joewiz** [comment]
@adamretter @duncdrum @dizzzz @line-o Thanks, guys!

**Pull request merged**
