### PR TITLE
General review, follow-on to mavenized documentation #342

### PR DESCRIPTION
**Pull request by joewiz**
~~DO NOT MERGE until https://github.com/eXist-db/documentation/pull/342 is merged. This is actually based off of that branch.~~

**Update (2018-05-22):** #342 was superseded by https://github.com/eXist-db/documentation/pull/349 (the `5.0.0-RC1` branch), so I rebased against it instead.

### CODE REVIEW

**Comment by joewiz** [comment]
I found a few URLs that still have problems:

```json
[
    {
        "404-errors": [
            {"backup.xml": "http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/tutorial-lesson-06.html"},
            {"beginners-guide-to-xrx-v4.xml": "http://localhost:8080/exist/apps/term/index.html"},
            {
                "scheduler.xml": {"href": "http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html"}
            },
            {
                "devguide_indexes.xml": [
                    "http://www.ordnancesurvey.co.uk/oswebsite/products/try-now/sample-data.html",
                    "http://www.vividsolutions.com/jts/bin/JTS%20Technical%20Specs.pdf",
                    "http://www.ordnancesurvey.co.uk/products/osmastermap/layers/topography/sampledata/2182-SS7886-2c1.gz",
                    "http://www.vividsolutions.com/jts/jtshome.htm"
                ]
            }
        ]
    },
    {
        "other-error": [
            {
                "deployment.xml": {
                    "error": "titanium.dstc.edu.au: nodename nor servname provided, or not known",
                    "href": "http://titanium.dstc.edu.au"
                }
            },
            {
                "xforms.xml": [
                    {
                        "error": "Connect to www.betterform.de:80 [www.betterform.de/212.204.63.100] failed: Operation timed out (Connection timed out)",
                        "href": "http://www.betterform.de"
                    },
                    {
                        "error": "Connect to betterform.de:80 [betterform.de/212.204.63.100] failed: Operation timed out (Connection timed out)",
                        "href": "http://betterform.de/trac"
                    },
                    {
                        "error": "Connect to betterform.de:80 [betterform.de/212.204.63.100] failed: Operation timed out (Connection timed out)",
                        "href": "http://betterform.de"
                    },
                    {
                        "error": "Connect to betterform.de:80 [betterform.de/212.204.63.100] failed: Operation timed out (Connection timed out)",
                        "href": "http://betterform.de/reports/Firefox-3.0-Mac-OS-X-10.6-ConformanceReport1.1.html",
                        "doc": "xforms.xml"
                    }
                ]
            },
            {
                "devguide_indexes.xml": [
                    {
                        "error": "geotools.codehaus.org: nodename nor servname provided, or not known",
                        "href": "http://geotools.codehaus.org/"
                    },
                    {
                        "error": "lists.refractions.net: nodename nor servname provided, or not known",
                        "href": "http://lists.refractions.net/m2/org/geotools/gt2-epsg-hsql/"
                    },
                    {
                        "error": "javadoc.geotools.fr: nodename nor servname provided, or not known",
                        "href": "http://javadoc.geotools.fr/snapshot/org/geotools/referencing/factory/epsg/FactoryOnHSQL.html"
                    }
                ]
            }
        ]
    }
]
```

Suggestions welcome!

**Comment by joewiz** [comment]
@duncdrum Great to hear. Sure, cherry pick away.

**Comment by joewiz** [comment]
Rebased against `5.0.0-RC1` branch.

**Comment by adamretter** [comment]
@joewiz @duncdrum Should I merge this, or some magic is still happening elsewhere?

**Comment by duncdrum** [comment]
lets fix the failing CI first

**Comment by joewiz** [comment]
@duncdrum Thanks for the nudge - I forgot to run `mvn test`...

**Pull request merged**
