### PR TITLE
output whole paragraphs in summary hit-list; make summary default view

### PR DESCRIPTION
**Pull request by jensopetersen**

### CODE REVIEW

**Comment by dizzzz** [comment]
@ljo is very close with the in java implementation of chic ; I'd like to have him involved.

**Comment by joewiz** [comment]
@dizzzz "chic"?

**Comment by dizzzz** [comment]
KWIC with spelling correction :-)

**Comment by adamretter** [comment]
IMHO - if this is ready, works and improve s the situation, we should merge it and not delay it for something that is not yet finished. It could be refactored for @ljo's changes when they are ready.

**Comment by jensopetersen** [comment]
Thanks for fitting this PR in. Special thanks to Joe for explaining what I was up to.
It is now more than a year since I have written a line of XQuery (or even looked at one), so I am reminded of days gone by …. 
Had a fun time working with eXist … and you guys.

**Comment by adamretter** [comment]
@jensopetersen Thanks Jens. I hope you are still having fun :-)

**Comment by adamretter** [comment]
@dizzzz So we can merge?

**Comment by dizzzz** [comment]
yes sure

**Comment by joewiz** [comment]
@jensopetersen Good to hear from you! Hope you're doing well!

**Pull request merged**
